[package]
name = "nannou_communication"
version = "0.1.0"
authors = ["Benjamin <ben@congdon.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.15"